### PR TITLE
Fix a few crashes while running shape inference

### LINKED ISSUE #6186: onnx.checker crashes on STFT
# Bug Report

### Describe the bug
```
#!/usr/bin/env python
import onnx
import onnx.parser

modeltxt = """
<
   ir_version: 10,
   opset_import: ["" : 17]
>
graph (float16[3] in0, int32[2] in1, float16[7,8,8,8] in2, int32[8,1,7,2] in3) => () {
   out0 = STFT (in0, in1, in2, in3)
}
"""

model = onnx.parser.parse_model(modeltxt)
print("Parser: Passed")
onnx.checker.check_model(model, full_check=True)
print("Checker: Passed")
onnx.shape_inference.infer_shapes(model)

```
crashes with
```
Parser: Passed
[1]    187375 segmentation fault  ./repro_bug.py
```

### System information
- OS Platform and Distribution (*. Linux Ubuntu 20.04*): Linux Ubuntu 20.04
- ONNX version (*e.g. 1.13*): 1.16.1
- Python version: 3.10.12

### Expected behavior
No crash, but an error that the model is invalid

### PR DESCRIPTION
**Pull request by xadupre**
### Description
Fixes #6186, #6185, #6180, #6187.

It also improves the error messages to let users know where something is going wrong.

### CODE REVIEW

File: onnx/defs/math/defs.cc [hunk 1]
```diff
@@ -3472,6 +3472,9 @@ ONNX_OPERATOR_SET_SCHEMA(
           }
 
           auto& input_shape = getInputShape(ctx, 0);
+          if (input_shape.dim_size() < 2) {
+            fail_shape_inference("First input should have at least 2 dimensions in ", ctx.getDisplayName(), ".");
```
Comment (justinchuby) [inline onnx/defs/math/defs.cc:3476]: Would it be helpful to print the actual dim? That’s usually what helps diagnose issues better

File: onnx/defs/nn/defs.cc [hunk 2]
```diff
@@ -126,6 +126,9 @@ void convPoolShapeInference(
             residual -= stride;
           }
         }
+        if (i >= static_cast<int>(effective_kernel_shape.size())) {
+          fail_shape_inference("kernel shape should have ", input_dims_size, " values in ", ctx.getDisplayName(), ".");
```
Comment (justinchuby) [inline onnx/defs/nn/defs.cc:130]:
```suggestion
          fail_shape_inference("kernel shape should have ", input_dims_size, " values in ", ctx.getDisplayName(), ".");
```

I would include the actual value

File: onnx/defs/nn/defs.cc [hunk 3]
```diff
@@ -959,19 +962,21 @@ ONNX_OPERATOR_SET_SCHEMA(
           auto w_type = ctx.getInputType(3);
           if (nullptr == x_type || nullptr == w_type || x_type->value_case() != TypeProto::kTensorType ||
               w_type->value_case() != TypeProto::kTensorType) {
-            fail_type_inference("inputs are expected to have tensor type.");
+            fail_type_inference("inputs are expected to have tensor type in ", ctx.getDisplayName(), ".");
```
Comment (justinchuby) [inline onnx/defs/nn/defs.cc:965]: […] not [actual type]

**Review by justinchuby — APPROVED** [review]
Thanks! I would recommend including the actual (invalid) values in all updated error messages applicable. I have found those to be the more helpful information in practice.

File: onnx/defs/shape_inference.h [hunk 4]
```diff
@@ -105,6 +105,8 @@ struct InferenceContext {
   virtual const SparseTensorProto* getInputSparseData(size_t index) const = 0;
   // Gets the shape inputs computed by partial data propagation.
   virtual const TensorShapeProto* getSymbolicInput(size_t index) const = 0;
+  // To display a name the user can use to narrow its search.
+  virtual std::string getDisplayName() const = 0;
```
Comment (gramalingam) [inline onnx/defs/shape_inference.h:109]: May be useful to provide a default implementation for backward compatibility (with other tools/implementations, like ORT). That way, they can add a custom implementation when they are ready.

Comment (gramalingam) [reply onnx/defs/shape_inference.h:109]: I mean even an empty string would be ok.

File: onnx/defs/nn/defs.cc (hunk 2 above)
Comment (xadupre) [reply onnx/defs/nn/defs.cc:130]: The message displays the kernel size. I think that's ok. Compare the existing error messages, this one is very verbose.

File: onnx/defs/shape_inference.h (hunk 4 above)
Comment (xadupre) [reply onnx/defs/shape_inference.h:109]: True.

File: onnx/defs/nn/defs.cc (hunk 3 above)
Comment (xadupre) [reply onnx/defs/nn/defs.cc:965]: The type is int. If we have a function which returns the type name, why not using it. Otherwise I prefer to let the message the way it is. All the error messages must be improved, not only this one.

Comment (xadupre) [reply onnx/defs/nn/defs.cc:965]: Another PR is necessary.

File: onnx/defs/math/defs.cc (hunk 1 above)
Comment (xadupre) [reply onnx/defs/math/defs.cc:3476]: We should review all the error messages. Let's keep that for another PR.

File: onnx/defs/shape_inference.h (hunk 4 above)
Comment (xadupre) [reply onnx/defs/shape_inference.h]: done

File: onnx/test/shape_inference_test.py [hunk 5]
```diff
@@ -1776,7 +1776,9 @@ def test_slice_with_input_shape_containing_dim_params(self) -> None:
                 make_tensor("ends", TensorProto.INT64, (3,), (1, 1, 1)),
             ],
         )
-        self._assert_inferred(graph, [make_tensor_value_info("y", TensorProto.FLOAT, (1, None, 1))])  # type: ignore
+        self._assert_inferred(
```
Comment (linkerzhang) [inline onnx/test/shape_inference_test.py:1779]: it may be better to move this kind of formatting changes in a separate PR.

Comment (linkerzhang) [inline onnx/test/shape_inference_test.py:1779]: it may be better to move this kind of formatting changes in a separate PR.

Comment (linkerzhang) [inline onnx/test/shape_inference_test.py:1779]: it may be better to move this kind of formatting changes in a separate PR.

Comment (xadupre) [reply onnx/test/shape_inference_test.py:1779]: I know. I wish I have a tool which can apply the same linting but lintrunner never worked for me.

Comment (xadupre) [reply onnx/test/shape_inference_test.py]: removed

Comment (xadupre) [reply onnx/test/shape_inference_test.py]: removed

Comment (xadupre) [reply onnx/test/shape_inference_test.py]: removed

**Review by gramalingam — APPROVED** [review]
