### PR TITLE
docs: fix window size type constraint wording

### LINKED ISSUE #4990: Document for Blackman Window
There is a conflict in the type spec: “T1 in ( tensor(int32), tensor(int64) ): Constrain the input size to int64_t.”

### PR DESCRIPTION
**Pull request by tsubasakong**
### Motivation and Context

Fixes #4990.

This updates the type-constraint description for HannWindow, HammingWindow, and BlackmanWindow from `int64_t` to `int32_t or int64_t` so the text matches the actual allowed types. Also updates generated operator/changelog docs accordingly.

### CODE REVIEW

File: onnx/defs/math/defs.cc [hunk 1]
```diff
@@ -2976,7 +2976,7 @@ ONNX_OPERATOR_SET_SCHEMA(
     17,
     OpSchema()
         .FillUsing(CosineSumWindowOpDocGenerator("Hamming"))
-        .TypeConstraint("T1", {"tensor(int32)", "tensor(int64)"}, "Constrain the input size to int64_t.")
+        .TypeConstraint("T1", {"tensor(int32)", "tensor(int64)"}, "Constrain the input size to int32_t or int64_t.")
```
Comment (gramalingam) [inline onnx/defs/math/defs.cc:2979]: Thanks for the fix. As a general comment (on this style used in the repo, not about this specific PR), I think specifying the types in the string is redundant, given that it is specified elsewhere. It should be used to describe *what* T1 is ("The type of input size" here), not what values it can take.
