### PR TITLE
Fix SegFault bug in shape inference

### LINKED ISSUE #5989: SegFault during shape inference if the schema not be set inference function
# Bug Report

### Describe the bug
SegFault during shape inference if the schema not be set inference function

### Reproduction instructions

cpp (Optional):

```
ONNX_OPERATOR_SCHEMA(CustomOp);
```

python:

```
import onnx
from onnx import defs

input = """
            <
                ir_version: 7,
                opset_import: [
                    "" : 1
                ]
            >
            agraph (float[N, 128] X, int32 Y) => (float[N] Z)
            {
                Z = CustomOp(X, Y)
            }
           """
model = onnx.parser.parse_model(input)

op_schema = defs.OpSchema(
    'CustomOp',
    '',
    1,
    inputs=[
    ],
    outputs=[
    ],
)

# Uncomment if not register in cpp
# onnx.defs.register_schema(op_schema)
onnx.shape_inference.infer_shapes(model, True)

```

### Expected behavior

Raise a python exception rather than crash.

### Notes

The root case is the input or output of schema is empty and the corresponding field in graph is no-empty. So the `input.back` from schema will invalid.

### PR DESCRIPTION
**Pull request by OYCN**
### Description

The bug is SegFault during shape inference if the schema not be set inference function.

The schema has `CheckInputOutputType` for shape inference and `Verify` for raw node proto. And the behavior is not fully aligned.

### Motivation and Context

fixes #5989

### CODE REVIEW

**Comment by justinchuby** [comment]
@cjvolzka @gramalingam may be worthy to be included in 1.16 since this is fixing a memory error.

File: onnx/defs/schema.cc [hunk 1]
```diff
@@ -107,6 +107,30 @@ OpSchemaRegistry* OpSchemaRegistry::Instance() {
 
 void OpSchema::CheckInputOutputType(struct InferenceContext& ctx) const {
   std::unordered_map<std::string, std::string> type_constraints;
+  if (inputs_.empty() && ctx.getNumInputs() > 0) {
```
Comment (gramalingam) [inline onnx/defs/schema.cc:110]: It would be more general to check that either inputs_ size equals ctx.getNumInputs() or that the last inputs_ is variadic.

**Review by gramalingam — APPROVED** [review]
The check can be made more general, as suggested in comments. But it's ok to merge this as is too, if we want to get this into the upcoming release.

**Comment by cjvolzka** [comment]
@justinchuby I can wait to cut rc2 until this has been cherry-picked into the `rel-1.16.0` branch.

File: onnx/defs/schema.cc [hunk 2]
```diff
@@ -107,6 +107,30 @@ OpSchemaRegistry* OpSchemaRegistry::Instance() {
...
+    fail_check(
+        "Node (",
+        domain(),
+        "::",
+        Name(),
+        ":",
+        since_version(),
+        ") need empty inputs, but got ",
+        ctx.getNumInputs(),
+        " in graph");
```
Comment (justinchuby) [inline onnx/defs/schema.cc:120]:
```suggestion
        ") takes zero inputs, but got ",
        ctx.getNumInputs(),
        " in graph");
```

File: onnx/defs/schema.cc [hunk 3]
```diff
@@ -107,6 +107,30 @@ OpSchemaRegistry* OpSchemaRegistry::Instance() {
...
+  }
+  if (outputs_.empty() && ctx.getNumOutputs() > 0) {
+    fail_check(
+        "Node (",
+        domain(),
+        "::",
+        Name(),
+        ":",
+        since_version(),
+        ") need empty outputs, but got ",
```
Comment (justinchuby) [inline onnx/defs/schema.cc:130]:
```suggestion
        ") yields zero outputs, but got ",
```

**Review by justinchuby — APPROVED** [review]

File: onnx/defs/schema.cc (hunk 1 above)
Comment (justinchuby) [reply onnx/defs/schema.cc:110]: Created https://github.com/onnx/onnx/issues/5993

**Comment by justinchuby** [comment]
I am going to merge as is for us to fix the bug, and then allow the author to create a follow-up.
